dist: xenial   # required for Python >= 3.7
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get install xsltproc
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then make PYTHON=python install; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then make PYTHON=python3 install; fi
script:
  - echo "OK"
